unused vars
blockapps/strato-getting-started pull request #101
Opened 2024-01-10 19:29 UTC by ayaabdelgawad

Remove the vars that are no longer required and should not prevent the start script from running. Adding in payment server var as required var

2024-01-10 19:42 UTC, jadariushill approved these changes

2024-01-11 03:24 UTC, nikitamendelbaum requested changes
Part of this is done in the develop branch that will be released together with STRATO. But making the STRIPE_PAYMENT_SERVER_URL a required value is still to be added there

2024-01-16 15:09 UTC, nikitamendelbaum commented
Closing in favor of the develop branch which already includes these changes.

2024-01-16 15:09 UTC, closed without merging

2024-01-16 15:09 UTC, nikitamendelbaum commented
Thanks @ayaabdelgawad !